version: "2" # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 250
  method-complexity:
    config:
      threshold: 100
  method-count:
    config:
      threshold: 200
  method-lines:
    config:
      threshold: 250
  nested-control-flow:
    config:
      threshold: 400
  return-statements:
    config:
      threshold: 400
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
  - "test/"
  - "src/data.js"
  - "node_modules/"
plugins:
  editorconfig:
    enabled: false
  eslint:
    enabled: false
  fixme:
    enabled: false
  nodesecurity:
    enabled: false
  shellcheck:
    enabled: false
  stylelint:
    enabled: false
