#!/bin/zsh

clear

echo "Atenção! "
echo ""
echo "Feche seus arquivos que estão abertos e pressione [ENTER]"
read enter
npx stylelint --fix ./src/zoo.js
wait
npx eslint --fix ./src/zoo.js
wait
npx prettier --write ./src/zoo.js
wait

