#!/bin/zsh

clear

# remove
echo "removendo coisas..."
rm -f ./package-lock.json 2>/dev/null
wait
rm -f ./.eslintignore 2>/dev/null
wait
rm -f ./.prettierignore 2>/dev/null
wait
rm -f ./.prettierrc 2>/dev/null
wait
rm -rf ./node_modules 2>/dev/null
wait
sleep 1

# update gitignore
echo "atualizando o gitignore..."
echo "node_modules/
instalar
package.json
package-lock.json
.stylelintignore
debug.js
corrigir
.prettierrc
.eslintrc
.prettierignore
.eslintignore" >./.gitignore
wait
sleep 1

# add eslintignore
echo "adicionando eslintignore..."
echo "node_modules
test" >./.eslintignore
wait
sleep 1

echo '
{
  "singleQuote": true,
  "semi": true,
  "proseWrap": "preserve"
}' >./.prettierrc
wait

# add eslintignore
echo "adicionando prettierignore..."
echo "node_modules
test" >./.prettierignore
wait
sleep 1

echo '
{
  "extends": "airbnb",
  "rules": {
    "no-console": "off",
    "prefer-arrow-callback": "off",
    "func-names": "off",
    "no-param-reassign": "off",
    "arrow-parens": ["error", "as-needed"]
  },
  "env": {
    "browser": true,
    "jest": true
  }
}
' >./.eslintrc


# install packages
echo "instalando alguns pacotes..."
npm remove eslint prettier eslint-config-airbnb eslint-plugin-import eslint-plugin-react eslint-plugin-jsx-a11y stylelint stylelint-config-standard
wait
rm -rf ./node_modules 2>/dev/null
wait
rm -f ./package-lock.json 2>/dev/null
wait
npm install --save-dev eslint prettier eslint-config-airbnb eslint-plugin-react eslint-plugin-import eslint-plugin-jsx-a11y stylelint stylelint-config-standard
wait
npm install
wait
npm audit fix
wait
sleep 1

# install packages
echo "adicionando permissão ao script..."
chmod +x ./corrigir
wait
sleep 1

# how use?
echo ""
echo "Como usar?"
echo "-> Escreva ./corrigir no terminal <-"
wait
sleep 1
